---
title: Local - global difference varying number of semantic clusters
subtitle: Native language clusters (average of both language pairs)
author: Molly Lewis 
date: "`r Sys.Date()`"
output:  
  html_document:
    toc_float: no
    code_folding: hide 
    number_sections: no
    toc: no
---

```{r setup, include = F}

# load packages
library(knitr)
library(rmarkdown)
library(tidyverse)
library(langcog)
library(here)

opts_chunk$set(echo = T, message = F, warning = F, 
               error = F, tidy = F, cache = F)

```


```{r}
ETS_CLUSTER_CORR_PATH <- here("analyses/11_native_cluster_control/data/mean_cluster_corrs_native/")


cluster_ets <- map_df(list.files(ETS_CLUSTER_CORR_PATH, full.names = T), 
                      ~read_csv(., col_names = c("cluster", "same",  "nclusters", "cor", "lang1", "lang2"))) %>%
  filter(!is.na(cor))

# aggregate within language pairs
language_pair_means_ets <- cluster_ets %>%
  group_by(nclusters, lang1, lang2, same) %>% 
  summarize(cor = mean(cor, na.rm = T))  %>% 
  mutate(corpus = "ets")
```




## ETS
```{r, fig.width = 9, fig.height = 4.5}
ets_ribbon_data <- language_pair_means_ets %>%
  group_by(same, nclusters) %>%
  multi_boot_standard(col = "cor", na.rm = T)  

ets_ribbon_data_for_plotting <- ets_ribbon_data %>%
  group_by(nclusters) %>%
  nest()%>%
  mutate(mean_max = map_dbl(data, ~filter(., same == "local") %>% pull(mean)),
         mean_min = map_dbl(data, ~filter(., same == "global") %>% pull(mean))) %>%
  unnest() %>%
  ungroup()


native_local_gloabl_plot <- ggplot(ets_ribbon_data_for_plotting, aes(x = nclusters, y = mean, color = same)) +
    geom_ribbon(aes(x = nclusters, ymin = mean_min, ymax = mean_max), 
                alpha = .1, color = "white") +
  geom_linerange(aes(ymin = ci_lower, max = ci_upper)) +
  geom_point(aes(shape = same), size = 4) +
  geom_line(size = 2) +
  annotate("text", x = 140, y = .36, label = 'atop(bold("local"))',
           color = "#E41A1C", size = 6, parse = TRUE) +
  annotate("text", x = 20, y = .24, label = 'atop(bold("global"))', 
           color = "#377EB8", size = 6, parse = T) +
  xlab("Number of Clusters (log)") +
  ylab("Word distance correlation") +
  scale_x_log10() +
  ylim(.15, .45) +
  #annotation_logticks() +
  scale_shape_manual("Comparison", values = c(15, 19)) +
  scale_color_manual("Comparison", values = c( "#377EB8", "#E41A1C")) +
 # facet_wrap(~corpus)+
  ylab("Cross-linguistic\nWord Distance Correlation") +
  theme_classic(base_size = 20) +
  theme(axis.line = element_line(size = 1.2),
        axis.ticks = element_line(size = 1),
        legend.position = "none")

FIG_OUTPATH <- here("analyses/11_cluster_control/results/figs/native_clustering_local_global.pdf")
pdf(FIG_OUTPATH)
native_local_gloabl_plot
dev.off()

```
