---
title: Wikipedia stats descriptive fig
author: Molly Lewis 
date: "`r Sys.Date()`"
output: 
  html_document:
    toc_float: no
    number_sections: no
    code_folding: hide
    toc: no
---

```{r setup, include = F}
# load packages
library(knitr)
library(rmarkdown)
library(tidyverse)
library(janitor)
library(here)
opts_chunk$set(echo = T, message = F, warning = F, 
               error = F, tidy = F, cache = F)
```


```{r}
PAGEVIEWS_PATH <- here("analyses/10_wikipedia_stats/data/processed/page_views_by_language.csv")
PRODUCITIVY_PATH <- here("analyses/10_wikipedia_stats/data/raw/wiki_productivity.csv")
NARTICLES_PATH <- here("analyses/10_wikipedia_stats/data/raw/num_articles.tsv")
LANG_NAMES <- here('analyses/04_predicting_semantic_sim/data/lang_distance_metrics/linguistic/data/iso_to_wals_for_ling_dists.csv')
OUTFILE <- here("analyses/10_wikipedia_stats/results/wiki_stats.pdf")

WIKI_LANGS <- c("ar", "bn", "bg", "zh", "nl", "en", "fr", "de", "el", "gu", "hi", "ig", "id", "it", "ja", "kn", "ko",
                "ml", "mr", "ne", "pa", "pl", "pt", "ro", "ru", "es", "tl", "ta", "te", "th", "tr", "ur", "vi", "yo",
                "fa")
```

```{r}
narticles <- read_tsv(NARTICLES_PATH) %>%
  clean_names() %>%
  select(language, wiki, articles, speakers, admins, active_users,
         percent_of_admins, depth, speakers_article) %>%
  mutate(speakers = as.numeric(str_remove_all(speakers, ","))) %>%
  filter(wiki %in% WIKI_LANGS)

productivity <- read_csv(PRODUCITIVY_PATH) %>%
  select(2,4) %>%
  mutate(potential_authors = potential_authors * 1000000)

page_views <- read_csv(PAGEVIEWS_PATH)

all_measures <- narticles %>%
  full_join(productivity, by = "wiki") %>%
  full_join(page_views, by = "wiki") %>%
  filter(!is.na(iso)) %>%
  filter(wiki %in% WIKI_LANGS) %>%
  select(-iso, -speakers_article, -percent_of_admins) %>%
  mutate_at(c("articles", "speakers", "speakers_l1", "total_requests", "potential_authors"), log) %>%
  mutate(prop_articles = articles/speakers_l1,
         prop_requests = total_requests/speakers_l1,
         productivity = articles/potential_authors) %>%
  select("wiki", "speakers", "speakers_l1", "potential_authors", "articles", "total_requests", "prop_articles",  "prop_requests", "productivity")

all_measures_long <- all_measures %>%
  pivot_longer(2:9) %>%
  mutate(name = fct_recode(name,
                               "N speakers \n (log)" = "speakers",
                               "N L1 speakers \n (log)" = "speakers_l1",
                                "N potential\nauthors (log)" = "potential_authors",
                               "N articles \n (log)" = "articles",
                               "N pageviews \n (log)" = "total_requests",
                               "Consumption\nrate" = "prop_requests",
                               "Productivity (1)" = "prop_articles",
                               "Productivity (2)"  = "productivity"),
          name = fct_relevel(name,  "N speakers \n (log)" , "N L1 speakers \n (log)",
                             "N potential\nauthors (log)" ,
                             "N articles \n (log)",
                                "N pageviews \n (log)", "Consumption\nrate", "Productivity (1)",
                                "Productivity (2)"))


full_width = 7.08661
pdf(OUTFILE, width = full_width, height  = 2.6)

ggplot(all_measures_long, aes(x = name, y = value, group = name)) +
  geom_violin(size = .3) +
  geom_point(alpha = .2) +
  facet_wrap(~name, scales = "free", nrow = 1) +
  theme_classic(base_size = 9) +
  ylab("") +
  xlab("\nWikipedia measure") +
  theme(strip.text = element_blank(),
        axis.ticks.x = element_blank())
dev.off()

         
```
